[bgcolor r=.02,g=.2,b=.6]

[font w=12, h=12, r=1,g=1,b=1]
How To Load Scripts:[nl][nl]
[font w=8, h=8, r=1,g=1,b=1]
First Open the 'AltMenu' by pressing and[nl]holding down the 'alt' key.[nl]
[image src='help/images/open_1.jpg',w=128,h=175][nl][nl]
Select the scripts folder you wish to browse[nl]
(you can choose server or client scripts).[nl]
[image src='help/images/open_2.jpg',w=128,h=175][nl][nl]
Scroll down until you find the script you want.[nl]
[image src='help/images/open_3.jpg',w=128,h=175][nl][nl]
Click on a script to execute it.[nl]
[image src='help/images/open_4.jpg',w=128,h=175][nl][nl]
Let go of the alt button to close the menu[nl]
and your all set. Your script should now be loaded.